// lib/extractors/xExtractor.ts
import puppeteer from "puppeteer";
import { GoogleGenerativeAI } from "@google/generative-ai";
import dotenv from "dotenv";

dotenv.config();

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "");

/**
 * Extracts all visible text from an X (Twitter) post using Puppeteer
 */
async function getFullTweetText(url: string): Promise<string> {
  console.log("🚀 Launching headless browser...");

  const browser = await puppeteer.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  });

  const page = await browser.newPage();
  console.log("🌐 Navigating to:", url);

  await page.goto(url, { waitUntil: "networkidle2", timeout: 60000 });

  try {
    console.log("⏳ Waiting for tweet content...");
    await page.waitForSelector("article div[lang]", { timeout: 15000 });

    const text = await page.$$eval("article div[lang]", (els) =>
      els.map((e) => (e.textContent || "").trim()).join("\n\n")
    );

    console.log("✅ Tweet captured successfully!");
    await browser.close();
    return text;
  } catch (err) {
    console.error("❌ Failed to extract tweet:", err);
    await browser.close();
    return "⚠️ Could not extract tweet content.";
  }
}

/**
 * Summarizes the extracted tweet text using Gemini
 */
async function summarizeWithGemini(tweetText: string, url: string): Promise<string> {
  if (!tweetText || tweetText === "⚠️ Could not extract tweet content.") {
    return "Could not summarize — tweet content unavailable.";
  }

  try {
    console.log("🧠 Sending tweet to Gemini for summarization...");

    const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });
    const prompt = `
You are a concise AI summarizer.
Summarize this X (Twitter) post into 2–3 lines, including tone and intent.

Tweet Content:
${tweetText}

URL: ${url}
`;

    const result = await model.generateContent(prompt);
    const summary = result.response.text().trim();

    console.log("✅ Gemini summary generated!");
    return summary || "⚠️ No summary generated by Gemini.";
  } catch (err) {
    console.error("❌ Gemini summarization failed:", err);
    return "⚠️ Failed to summarize tweet.";
  }
}

/**
 * Main entry — called by /lib/extractors/index.ts
 */
export async function extractXSummary(url: string): Promise<string> {
  console.log("🐦 Extracting X (Twitter) summary for:", url);

  const tweetText = await getFullTweetText(url);
  const summary = await summarizeWithGemini(tweetText, url);

  return summary;
}
